import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import { BottomNavigationBar } from "@/components/bottom-navigation-bar";
import { Navbar } from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark w-full h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-full h-full flex antialiased overscroll-none overflow-hidden`}
      >
        <Sidebar/>
        <div className="flex flex-1 flex-col">
          <Navbar />
          {children}
          <BottomNavigationBar />
        </div>
      </body>
    </html>
  );
}



