import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ArrowUpDown, CreditCard, Folder, House, Plus } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark w-full h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-full h-full flex antialiased overscroll-none overflow-hidden`}
      >
        <Sidebar/>
        <div className="flex flex-1 flex-col">
          <Navbar />
          {children}
          <BottomNavigationBar />
        </div>
      </body>
    </html>
  );
}

function Navbar() {
  return (
    <div className="sticky w-full p-3 flex items-center justify-center border-b">
      <p>SIDEBAR</p>
    </div>
  );
}

function Sidebar(){
  return(
    <div className="hidden md:flex w-[350px] h-screen border-r" />
  )
}
function BottomNavigationBar() {
  return (
    <div className="min-h-[100px] w-full  flex md:hidden items-center justify-evenly border-t">
      <House/>
      <Folder/>
      <div className="bg-zinc-800 p-3 rounded-full">
        <Plus/>
        </div>
      <ArrowUpDown/>
      <CreditCard/>
    </div>
  );
}
